### ISSUE TITLE
This is a deep copy

### ISSUE THREAD

**Issue by eush77** [bredele/shallow#3]
If I'm not mistaken, this module actually returns a deep copy of its argument.

```js
> a = { o: { k: 1 } }
{ o: { k: 1 } }
> b = shallow(a)
{ o: { k: 1 } }
> a.o.k = 2
2
> b
{ o: { k: 1 } }
```

You should remove recursive call on line 27 if you want this module to perform [shallow] copy.

[shallow]: http://en.wikipedia.org/wiki/Object_copy#Shallow_copy

**Comment by bredele** [comment]
@eush77 you are right :) I was just looking for a name that wasn't taken in the npm registry :p

**Comment by eush77** [comment]
Could you state that in the description.

**Comment by bredele** [comment]
@eush77 :+1:  thanks for your feedback
